language: sh
matrix:
  include:
    - os: linux
      dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y bash binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
  - git clone https://github.com/SimonKagstrom/kcov.git
  - cd kcov
  - mkdir build; cd build; cmake ..; make -j4; sudo make install
  - cd ../..
  - docker pull jclaveau/php-multiversion:0.5.2
  - docker pull jclaveau/php-multiversion:latest
  - curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/master/setup.sh" | bash
  - echo $PATH
  - PATH=/home/travis/.local/bin:$PATH
script:
  - shellcheck -x bin/* lib/*
  - bpkg install -g jclaveau/docker-php-multiversion
  - . ~/.profile
  - command -v php
  - git clone https://github.com/shellspec/shellspec.git
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage;
