language: sh
matrix:
  include:
    - os: linux
      dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y bash binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
  - git clone https://github.com/SimonKagstrom/kcov.git
  - cd kcov
  - mkdir build; cd build; cmake ..; make -j4; sudo make install
  - cd ../..
  - docker pull jclaveau/php-multiversion:0.3.0
  - docker pull jclaveau/php-multiversion:latest
  - sudo curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/master/setup.sh" | sudo bash
script:
  - shellcheck -x php lib/functions.bash
  - sudo make
  - sudo make uninstall
  - sudo bpkg install -g jclaveau/docker-php-multiversion
  - make check
after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage;
