language: sh
matrix:
  include:
    - os: linux
      dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y bash binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
  - git clone https://github.com/SimonKagstrom/kcov.git
  - cd kcov
  - mkdir build; cd build; cmake ..; make -j4; sudo make install
  - cd ../..
  - docker pull jclaveau/php-multiversion:0.2.0
script:
  - sudo make
after_success:
  - bash <(curl -s https://codecov.io/bash) -s coverage;
