language: sh
services:
 - docker
jobs:
  include:
  - name: "latest"
    env: PHP_MULTIVERSION_IMAGE="latest"
    os: linux
    dist: xenial
  # - name: "stable"
    # env: PHP_MULTIVERSION_IMAGE=
    # os: linux
    # dist: xenial
# before_install:
  # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  # - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  # - sudo apt-get update
  # - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - bash contrib/travis_before_script.sh
  - docker pull jclaveau/php-multiversion:"$PHP_MULTIVERSION_IMAGE"
  - curl -Lo- "https://raw.githubusercontent.com/bpkg/bpkg/master/setup.sh" | bash
  - echo $PATH
  - PATH=/home/travis/.local/bin:$PATH
  - shellcheck -x bin/* lib/*
  - bpkg install -g jclaveau/docker-php-multiversion
  - . ~/.profile
  - command -v php
  # - docker network create -d bridge web
  - php container-ip
  - php container-exec cat /etc/hosts
  # - curl http://localhost:7056/spec/phpversion.php
  - curl http://"$(php container-ip)":7056/spec/phpversion.php
  - make test
  - cat log/nginx/error.log 
  - cat log/nginx/access.log 

after_success:
  - if [ -z "$PHP_MULTIVERSION_IMAGE" ]; then bash <(curl -s https://codecov.io/bash) -s coverage; fi
