#!/bin/bash

docker image build \
    -t jclaveau/php-multiversion:latest \
    .

# sudo apt install gnupg2 pass
# docker login
cat << EOF
Push to Docker Hub with:

docker image push jclaveau/php-multiversion:latest

EOF
