#!/bin/bash

(docker image build \
    -t jclaveau/php-multiversion:latest \
    . \
     | tee build.stdout.log) 3>&1 1>&2 2>&3 | tee build.stderr.log

php kill-containers

PHP_MULTIVERSION_IMAGE='latest'
PHP_MULTIVERSION_IMAGE="$PHP_MULTIVERSION_IMAGE" shellspec
shellspec_result=$?

if [ $shellspec_result == 0 ]; then
    # sudo apt install gnupg2 pass
    # docker login
    cat << EOF
Push to Docker Hub with:

docker image push jclaveau/php-multiversion:$PHP_MULTIVERSION_IMAGE

docker images | grep jclaveau/php-multiversion
docker tag <id> jclaveau/php-multiversion:X.X.X
docker image push jclaveau/php-multiversion:X.X.X
EOF
fi
